INSERT INTO locations VALUES ( '0','NS1 EW24','Jurong East');
INSERT INTO locations VALUES ( '1','NS2','Bukit Batok');
INSERT INTO locations VALUES ( '2','NS3','Bukit Gombak');
INSERT INTO locations VALUES ( '3','NS4 BP1','Choa Chu Kang');
INSERT INTO locations VALUES ( '4','NS5','Yew Tee');
INSERT INTO locations VALUES ( '5','NS7','Kranji');
INSERT INTO locations VALUES ( '6','NS8','Marsiling');
INSERT INTO locations VALUES ( '7','NS9 TE2','Woodlands');
INSERT INTO locations VALUES ( '8','NS10','Admiralty');
INSERT INTO locations VALUES ( '9','NS11','Sembawang');
INSERT INTO locations VALUES ( '10','NS12','Canberra');
INSERT INTO locations VALUES ( '11','NS13','Yishun');
INSERT INTO locations VALUES ( '12','NS14','Khatib');
INSERT INTO locations VALUES ( '13','NS15','Yio Chu Kang');
INSERT INTO locations VALUES ( '14','NS16','Ang Mo Kio');
INSERT INTO locations VALUES ( '15','NS17 CC15','Bishan');
INSERT INTO locations VALUES ( '16','NS18','Braddell');
INSERT INTO locations VALUES ( '17','NS19','Toa Payoh');
INSERT INTO locations VALUES ( '18','NS20','Novena');
INSERT INTO locations VALUES ( '19','NS21 DT11','Newton');
INSERT INTO locations VALUES ( '20','NS22','Orchard');
INSERT INTO locations VALUES ( '21','NS23','Somerset');
INSERT INTO locations VALUES ( '22','NS24 NE6 CC1','Dhoby Ghaut');
INSERT INTO locations VALUES ( '23','NS25 EW13','City Hall');
INSERT INTO locations VALUES ( '24','NS26 EW14','Raffles Place');
INSERT INTO locations VALUES ( '25','NS27 CE2','Marina Bay');
INSERT INTO locations VALUES ( '26','NS28','Marina South Pier');
INSERT INTO locations VALUES ( '27','EW1','Pasir Ris');
INSERT INTO locations VALUES ( '28','EW2 DT32','Tampines');
INSERT INTO locations VALUES ( '29','EW3','Simei');
INSERT INTO locations VALUES ( '30','EW4 CG','Tanah Merah');
INSERT INTO locations VALUES ( '31','EW5','Bedok');
INSERT INTO locations VALUES ( '32','EW6','Kembangan');
INSERT INTO locations VALUES ( '33','EW7','Eunos');
INSERT INTO locations VALUES ( '34','EW8 CC9','Paya Lebar');
INSERT INTO locations VALUES ( '35','EW9','Aljunied');
INSERT INTO locations VALUES ( '36','EW10','Kallang');
INSERT INTO locations VALUES ( '37','EW11','Lavender');
INSERT INTO locations VALUES ( '38','EW12 DT14','Bugis');
INSERT INTO locations VALUES ( '39','EW13 NS25','City Hall');
INSERT INTO locations VALUES ( '40','EW14 NS26','Raffles Place');
INSERT INTO locations VALUES ( '41','EW15','Tanjong Pagar');
INSERT INTO locations VALUES ( '42','EW16 NE3','Outram Park');
INSERT INTO locations VALUES ( '43','EW17','Tiong Bahru');
INSERT INTO locations VALUES ( '44','EW18','Redhill');
INSERT INTO locations VALUES ( '45','EW19','Queenstown');
INSERT INTO locations VALUES ( '46','EW20','Commonwealth');
INSERT INTO locations VALUES ( '47','EW21 CC22','Buona Vista');
INSERT INTO locations VALUES ( '48','EW22','Dover');
INSERT INTO locations VALUES ( '49','EW23','Clementi');
INSERT INTO locations VALUES ( '50','EW24 NS1','Jurong East');
INSERT INTO locations VALUES ( '51','EW25','Chinese Garden');
INSERT INTO locations VALUES ( '52','EW26','Lakeside');
INSERT INTO locations VALUES ( '53','EW27','Boon Lay');
INSERT INTO locations VALUES ( '54','EW28','Pioneer');
INSERT INTO locations VALUES ( '55','EW29','Joo Koon');
INSERT INTO locations VALUES ( '56','EW30','Gul Circle');
INSERT INTO locations VALUES ( '57','EW31','Tuas Crescent');
INSERT INTO locations VALUES ( '58','EW32','Tuas West Road');
INSERT INTO locations VALUES ( '59','EW33','Tuas Link');
INSERT INTO locations VALUES ( '60','CG1 DT35','Expo');
INSERT INTO locations VALUES ( '61','CG2','Changi Airport');
INSERT INTO locations VALUES ( '62','NE1 CC29','HarbourFront');
INSERT INTO locations VALUES ( '63','NE3 EW16','Outram Park');
INSERT INTO locations VALUES ( '64','NE4 DT19','Chinatown');
INSERT INTO locations VALUES ( '65','NE5','Clarke Quay');
INSERT INTO locations VALUES ( '66','NE6 NS24 CC1','Dhoby Ghaut');
INSERT INTO locations VALUES ( '67','NE7 DT12','Little India');
INSERT INTO locations VALUES ( '68','NE8','Farrer Park');
INSERT INTO locations VALUES ( '69','NE9','Boon Keng');
INSERT INTO locations VALUES ( '70','NE10','Potong Pasir');
INSERT INTO locations VALUES ( '71','NE11','Woodleigh');
INSERT INTO locations VALUES ( '72','NE12 CC13','Serangoon');
INSERT INTO locations VALUES ( '73','NE13','Kovan');
INSERT INTO locations VALUES ( '74','NE14','Hougang');
INSERT INTO locations VALUES ( '75','NE15','Buangkok');
INSERT INTO locations VALUES ( '76','NE16 STC','Sengkang');
INSERT INTO locations VALUES ( '77','NE17 PTC','Punggol');
INSERT INTO locations VALUES ( '78','CC1 NS24 NE6','Dhoby Ghaut');
INSERT INTO locations VALUES ( '79','CC2','Bras Basah');
INSERT INTO locations VALUES ( '80','CC3','Esplanade');
INSERT INTO locations VALUES ( '81','CC4 DT15','Promenade');
INSERT INTO locations VALUES ( '82','CC5','Nicoll Highway');
INSERT INTO locations VALUES ( '83','CC6','Stadium');
INSERT INTO locations VALUES ( '84','CC7','Mountbatten');
INSERT INTO locations VALUES ( '85','CC8','Dakota');
INSERT INTO locations VALUES ( '86','CC9 EW8','Paya Lebar');
INSERT INTO locations VALUES ( '87','CC10 DT26','MacPherson');
INSERT INTO locations VALUES ( '88','CC11','Tai Seng');
INSERT INTO locations VALUES ( '89','CC12','Bartley');
INSERT INTO locations VALUES ( '90','CC13 NE12','Serangoon');
INSERT INTO locations VALUES ( '91','CC14','Lorong Chuan');
INSERT INTO locations VALUES ( '92','CC15 NS17','Bishan');
INSERT INTO locations VALUES ( '93','CC16','Marymount');
INSERT INTO locations VALUES ( '94','CC17','Caldecott');
INSERT INTO locations VALUES ( '95','CC19 DT9','Botanic Gardens');
INSERT INTO locations VALUES ( '96','CC20','Farrer Road');
INSERT INTO locations VALUES ( '97','CC21','Holland Village');
INSERT INTO locations VALUES ( '98','CC22 EW21','Buona Vista');
INSERT INTO locations VALUES ( '99','CC23','one-north');
INSERT INTO locations VALUES ( '100','CC24','Kent Ridge');
INSERT INTO locations VALUES ( '101','CC25','Haw Par Villa');
INSERT INTO locations VALUES ( '102','CC26','Pasir Panjang');
INSERT INTO locations VALUES ( '103','CC27','Labrador Park');
INSERT INTO locations VALUES ( '104','CC28','Telok Blangah');
INSERT INTO locations VALUES ( '105','CC29 NE1','HarbourFront');
INSERT INTO locations VALUES ( '106','CE1 DT16','Bayfront');
INSERT INTO locations VALUES ( '107','CE2 NS27','Marina Bay');
INSERT INTO locations VALUES ( '108','DT1 BP6','Bukit Panjang');
INSERT INTO locations VALUES ( '109','DT2','Cashew');
INSERT INTO locations VALUES ( '110','DT3','Hillview');
INSERT INTO locations VALUES ( '111','DT5','Beauty World');
INSERT INTO locations VALUES ( '112','DT6','King Albert Park');
INSERT INTO locations VALUES ( '113','DT7','Sixth Avenue');
INSERT INTO locations VALUES ( '114','DT8','Tan Kah Kee');
INSERT INTO locations VALUES ( '115','DT9 CC19','Botanic Gardens');
INSERT INTO locations VALUES ( '116','DT10','Stevens');
INSERT INTO locations VALUES ( '117','DT11 NS21','Newton');
INSERT INTO locations VALUES ( '118','DT12 NE7','Little India');
INSERT INTO locations VALUES ( '119','DT13','Rochor');
INSERT INTO locations VALUES ( '120','DT14 EW12','Bugis');
INSERT INTO locations VALUES ( '121','DT15 CC4','Promenade');
INSERT INTO locations VALUES ( '122','DT16 CE1','Bayfront');
INSERT INTO locations VALUES ( '123','DT17','Downtown');
INSERT INTO locations VALUES ( '124','DT18','Telok Ayer');
INSERT INTO locations VALUES ( '125','DT19 NE4','Chinatown');
INSERT INTO locations VALUES ( '126','DT20','Fort Canning');
INSERT INTO locations VALUES ( '127','DT21','Bencoolen');
INSERT INTO locations VALUES ( '128','DT22','Jalan Besar');
INSERT INTO locations VALUES ( '129','DT23','Bendemeer');
INSERT INTO locations VALUES ( '130','DT24','Geylang Bahru');
INSERT INTO locations VALUES ( '131','DT25','Mattar');
INSERT INTO locations VALUES ( '132','DT26 CC10','MacPherson');
INSERT INTO locations VALUES ( '133','DT27','Ubi');
INSERT INTO locations VALUES ( '134','DT28','Kaki Bukit');
INSERT INTO locations VALUES ( '135','DT29','Bedok North');
INSERT INTO locations VALUES ( '136','DT30','Bedok Reservoir');
INSERT INTO locations VALUES ( '137','DT31','Tampines West');
INSERT INTO locations VALUES ( '138','DT32 EW2','Tampines');
INSERT INTO locations VALUES ( '139','DT33','Tampines East');
INSERT INTO locations VALUES ( '140','DT34','Upper Changi');
INSERT INTO locations VALUES ( '141','DT35 CG1','Expo');
INSERT INTO locations VALUES ( '142','TE1 RTS','Woodlands North');
INSERT INTO locations VALUES ( '143','TE2 NS9','Woodlands');
INSERT INTO locations VALUES ( '144','TE3','Woodlands South');
