INSERT INTO locations(location_id,location_name) VALUES (1,'Jurong East');
INSERT INTO locations(location_id,location_name) VALUES (2,'Bukit Batok');
INSERT INTO locations(location_id,location_name) VALUES (3,'Bukit Gombak');
INSERT INTO locations(location_id,location_name) VALUES (4,'Choa Chu Kang');
INSERT INTO locations(location_id,location_name) VALUES (5,'Yew Tee');
INSERT INTO locations(location_id,location_name) VALUES (6,'Kranji');
INSERT INTO locations(location_id,location_name) VALUES (7,'Marsiling');
INSERT INTO locations(location_id,location_name) VALUES (8,'Woodlands');
INSERT INTO locations(location_id,location_name) VALUES (9,'Admiralty');
INSERT INTO locations(location_id,location_name) VALUES (10,'Sembawang');
INSERT INTO locations(location_id,location_name) VALUES (11,'Yishun');
INSERT INTO locations(location_id,location_name) VALUES (12,'Khatib');
INSERT INTO locations(location_id,location_name) VALUES (13,'Yio Chu Kang');
INSERT INTO locations(location_id,location_name) VALUES (14,'Ang Mo Kio');
INSERT INTO locations(location_id,location_name) VALUES (15,'Bishan');
INSERT INTO locations(location_id,location_name) VALUES (16,'Braddell');
INSERT INTO locations(location_id,location_name) VALUES (17,'Toa Payoh');
INSERT INTO locations(location_id,location_name) VALUES (18,'Novena');
INSERT INTO locations(location_id,location_name) VALUES (19,'Newton');
INSERT INTO locations(location_id,location_name) VALUES (20,'Orchard');
INSERT INTO locations(location_id,location_name) VALUES (21,'Somerset');
INSERT INTO locations(location_id,location_name) VALUES (22,'Dhoby Ghaut');
INSERT INTO locations(location_id,location_name) VALUES (23,'City Hall');
INSERT INTO locations(location_id,location_name) VALUES (24,'Raffles Place');
INSERT INTO locations(location_id,location_name) VALUES (25,'Marina Bay');
INSERT INTO locations(location_id,location_name) VALUES (26,'Marina South Pier');
INSERT INTO locations(location_id,location_name) VALUES (27,'Pasir Ris');
INSERT INTO locations(location_id,location_name) VALUES (28,'Tampines');
INSERT INTO locations(location_id,location_name) VALUES (29,'Simei');
INSERT INTO locations(location_id,location_name) VALUES (30,'Tanah Merah');
INSERT INTO locations(location_id,location_name) VALUES (31,'Bedok');
INSERT INTO locations(location_id,location_name) VALUES (32,'Kembangan');
INSERT INTO locations(location_id,location_name) VALUES (33,'Eunos');
INSERT INTO locations(location_id,location_name) VALUES (34,'Paya Lebar');
INSERT INTO locations(location_id,location_name) VALUES (35,'Aljunied');
INSERT INTO locations(location_id,location_name) VALUES (36,'Kallang');
INSERT INTO locations(location_id,location_name) VALUES (37,'Lavender');
INSERT INTO locations(location_id,location_name) VALUES (38,'Bugis');
INSERT INTO locations(location_id,location_name) VALUES (39,'City Hall');
INSERT INTO locations(location_id,location_name) VALUES (40,'Raffles Place');
INSERT INTO locations(location_id,location_name) VALUES (41,'Tanjong Pagar');
INSERT INTO locations(location_id,location_name) VALUES (42,'Outram Park');
INSERT INTO locations(location_id,location_name) VALUES (43,'Tiong Bahru');
INSERT INTO locations(location_id,location_name) VALUES (44,'Redhill');
INSERT INTO locations(location_id,location_name) VALUES (45,'Queenstown');
INSERT INTO locations(location_id,location_name) VALUES (46,'Commonwealth');
INSERT INTO locations(location_id,location_name) VALUES (47,'Buona Vista');
INSERT INTO locations(location_id,location_name) VALUES (48,'Dover');
INSERT INTO locations(location_id,location_name) VALUES (49,'Clementi');
INSERT INTO locations(location_id,location_name) VALUES (50,'Jurong East');
INSERT INTO locations(location_id,location_name) VALUES (51,'Chinese Garden');
INSERT INTO locations(location_id,location_name) VALUES (52,'Lakeside');
INSERT INTO locations(location_id,location_name) VALUES (53,'Boon Lay');
INSERT INTO locations(location_id,location_name) VALUES (54,'Pioneer');
INSERT INTO locations(location_id,location_name) VALUES (55,'Joo Koon');
INSERT INTO locations(location_id,location_name) VALUES (56,'Tuas Crescent');
INSERT INTO locations(location_id,location_name) VALUES (57,'Tuas West Road');
INSERT INTO locations(location_id,location_name) VALUES (58,'Tuas Link');
INSERT INTO locations(location_id,location_name) VALUES (59,'Expo');
INSERT INTO locations(location_id,location_name) VALUES (60,'Changi Airport');
INSERT INTO locations(location_id,location_name) VALUES (61,'HarbourFront');
INSERT INTO locations(location_id,location_name) VALUES (62,'Outram Park');
INSERT INTO locations(location_id,location_name) VALUES (63,'Chinatown');
INSERT INTO locations(location_id,location_name) VALUES (64,'Clarke Quay');
INSERT INTO locations(location_id,location_name) VALUES (65,'Dhoby Ghaut');
INSERT INTO locations(location_id,location_name) VALUES (66,'Little India');
INSERT INTO locations(location_id,location_name) VALUES (67,'Farrer Park');
INSERT INTO locations(location_id,location_name) VALUES (68,'Boon Keng');
INSERT INTO locations(location_id,location_name) VALUES (69,'Potong Pasir');
INSERT INTO locations(location_id,location_name) VALUES (70,'Woodleigh');
INSERT INTO locations(location_id,location_name) VALUES (71,'Serangoon');
INSERT INTO locations(location_id,location_name) VALUES (72,'Kovan');
INSERT INTO locations(location_id,location_name) VALUES (73,'Hougang');
INSERT INTO locations(location_id,location_name) VALUES (74,'Buangkok');
INSERT INTO locations(location_id,location_name) VALUES (75,'Sengkang');
INSERT INTO locations(location_id,location_name) VALUES (76,'Punggol');
INSERT INTO locations(location_id,location_name) VALUES (77,'Dhoby Ghaut');
INSERT INTO locations(location_id,location_name) VALUES (78,'Bras Basah');
INSERT INTO locations(location_id,location_name) VALUES (79,'Esplanade');
INSERT INTO locations(location_id,location_name) VALUES (80,'Promenade');
INSERT INTO locations(location_id,location_name) VALUES (81,'Nicoll Highway');
INSERT INTO locations(location_id,location_name) VALUES (82,'Stadium');
INSERT INTO locations(location_id,location_name) VALUES (83,'Mountbatten');
INSERT INTO locations(location_id,location_name) VALUES (84,'Dakota');
INSERT INTO locations(location_id,location_name) VALUES (85,'Paya Lebar');
INSERT INTO locations(location_id,location_name) VALUES (86,'MacPherson');
INSERT INTO locations(location_id,location_name) VALUES (87,'Tai Seng');
INSERT INTO locations(location_id,location_name) VALUES (88,'Bartley');
INSERT INTO locations(location_id,location_name) VALUES (89,'Serangoon');
INSERT INTO locations(location_id,location_name) VALUES (90,'Lorong Chuan');
INSERT INTO locations(location_id,location_name) VALUES (91,'Bishan');
INSERT INTO locations(location_id,location_name) VALUES (92,'Marymount');
INSERT INTO locations(location_id,location_name) VALUES (93,'Caldecott');
INSERT INTO locations(location_id,location_name) VALUES (94,'Botanic Gardens');
INSERT INTO locations(location_id,location_name) VALUES (95,'Farrer Road');
INSERT INTO locations(location_id,location_name) VALUES (96,'Holland Village');
INSERT INTO locations(location_id,location_name) VALUES (97,'Buona Vista');
INSERT INTO locations(location_id,location_name) VALUES (98,'one-north');
INSERT INTO locations(location_id,location_name) VALUES (99,'Kent Ridge');
INSERT INTO locations(location_id,location_name) VALUES (100,'Haw Par Villa');
INSERT INTO locations(location_id,location_name) VALUES (101,'Pasir Panjang');
INSERT INTO locations(location_id,location_name) VALUES (102,'Labrador Park');
INSERT INTO locations(location_id,location_name) VALUES (103,'Telok Blangah');
INSERT INTO locations(location_id,location_name) VALUES (104,'HarbourFront');
INSERT INTO locations(location_id,location_name) VALUES (105,'Bayfront');
INSERT INTO locations(location_id,location_name) VALUES (106,'Marina Bay');
INSERT INTO locations(location_id,location_name) VALUES (107,'Bukit Panjang');
INSERT INTO locations(location_id,location_name) VALUES (108,'Cashew');
INSERT INTO locations(location_id,location_name) VALUES (109,'Hillview');
INSERT INTO locations(location_id,location_name) VALUES (110,'Beauty World');
INSERT INTO locations(location_id,location_name) VALUES (111,'King Albert Park');
INSERT INTO locations(location_id,location_name) VALUES (112,'Sixth Avenue');
INSERT INTO locations(location_id,location_name) VALUES (113,'Tan Kah Kee');
INSERT INTO locations(location_id,location_name) VALUES (114,'Botanic Gardens');
INSERT INTO locations(location_id,location_name) VALUES (115,'Stevens');
INSERT INTO locations(location_id,location_name) VALUES (116,'Newton');
INSERT INTO locations(location_id,location_name) VALUES (117,'Little India');
INSERT INTO locations(location_id,location_name) VALUES (118,'Rochor');
INSERT INTO locations(location_id,location_name) VALUES (119,'Bugis');
INSERT INTO locations(location_id,location_name) VALUES (120,'Promenade');
INSERT INTO locations(location_id,location_name) VALUES (121,'Bayfront');
INSERT INTO locations(location_id,location_name) VALUES (122,'Downtown');
INSERT INTO locations(location_id,location_name) VALUES (123,'Telok Ayer');
INSERT INTO locations(location_id,location_name) VALUES (124,'Chinatown');
INSERT INTO locations(location_id,location_name) VALUES (125,'Fort Canning');
INSERT INTO locations(location_id,location_name) VALUES (126,'Bencoolen');
INSERT INTO locations(location_id,location_name) VALUES (127,'Jalan Besar');
INSERT INTO locations(location_id,location_name) VALUES (128,'Bendemeer');
INSERT INTO locations(location_id,location_name) VALUES (129,'Geylang Bahru');
INSERT INTO locations(location_id,location_name) VALUES (130,'Mattar');
INSERT INTO locations(location_id,location_name) VALUES (131,'MacPherson');
INSERT INTO locations(location_id,location_name) VALUES (132,'Ubi');
INSERT INTO locations(location_id,location_name) VALUES (133,'Kaki Bukit');
INSERT INTO locations(location_id,location_name) VALUES (134,'Bedok North');
INSERT INTO locations(location_id,location_name) VALUES (135,'Bedok Reservoir');
INSERT INTO locations(location_id,location_name) VALUES (136,'Tampines West');
INSERT INTO locations(location_id,location_name) VALUES (137,'Tampines');
INSERT INTO locations(location_id,location_name) VALUES (138,'Tampines East');
INSERT INTO locations(location_id,location_name) VALUES (139,'Upper Changi');
INSERT INTO locations(location_id,location_name) VALUES (140,'Expo');
INSERT INTO locations(location_id,location_name) VALUES (141,'Woodlands North');
INSERT INTO locations(location_id,location_name) VALUES (142,'Woodlands South');
INSERT INTO locations(location_id,location_name) VALUES (143,'Canberra');
INSERT INTO locations(location_id,location_name) VALUES (144,'MacPherson');
INSERT INTO locations(location_id,location_name) VALUES (145,'Gul Circle');
