INSERT INTO locations(location_id,location_name) VALUES (1,'Admiralty');
INSERT INTO locations(location_id,location_name) VALUES (2,'Aljunied');
INSERT INTO locations(location_id,location_name) VALUES (3,'Ang Mo Kio');
INSERT INTO locations(location_id,location_name) VALUES (4,'Bartley');
INSERT INTO locations(location_id,location_name) VALUES (5,'Bayfront');
INSERT INTO locations(location_id,location_name) VALUES (6,'Beauty World');
INSERT INTO locations(location_id,location_name) VALUES (7,'Bedok North');
INSERT INTO locations(location_id,location_name) VALUES (8,'Bedok Reservoir');
INSERT INTO locations(location_id,location_name) VALUES (9,'Bedok');
INSERT INTO locations(location_id,location_name) VALUES (10,'Bencoolen');
INSERT INTO locations(location_id,location_name) VALUES (11,'Bendemeer');
INSERT INTO locations(location_id,location_name) VALUES (12,'Bishan');
INSERT INTO locations(location_id,location_name) VALUES (13,'Boon Keng');
INSERT INTO locations(location_id,location_name) VALUES (14,'Boon Lay');
INSERT INTO locations(location_id,location_name) VALUES (15,'Botanic Gardens');
INSERT INTO locations(location_id,location_name) VALUES (16,'Braddell');
INSERT INTO locations(location_id,location_name) VALUES (17,'Bras Basah');
INSERT INTO locations(location_id,location_name) VALUES (18,'Buangkok');
INSERT INTO locations(location_id,location_name) VALUES (19,'Bugis');
INSERT INTO locations(location_id,location_name) VALUES (20,'Bukit Batok');
INSERT INTO locations(location_id,location_name) VALUES (21,'Bukit Gombak');
INSERT INTO locations(location_id,location_name) VALUES (22,'Bukit Panjang');
INSERT INTO locations(location_id,location_name) VALUES (23,'Buona Vista');
INSERT INTO locations(location_id,location_name) VALUES (24,'Caldecott');
INSERT INTO locations(location_id,location_name) VALUES (25,'Canberra');
INSERT INTO locations(location_id,location_name) VALUES (26,'Cashew');
INSERT INTO locations(location_id,location_name) VALUES (27,'Changi Airport');
INSERT INTO locations(location_id,location_name) VALUES (28,'Chinatown');
INSERT INTO locations(location_id,location_name) VALUES (29,'Chinese Garden');
INSERT INTO locations(location_id,location_name) VALUES (30,'Choa Chu Kang');
INSERT INTO locations(location_id,location_name) VALUES (31,'City Hall');
INSERT INTO locations(location_id,location_name) VALUES (32,'Clarke Quay');
INSERT INTO locations(location_id,location_name) VALUES (33,'Clementi');
INSERT INTO locations(location_id,location_name) VALUES (34,'Commonwealth');
INSERT INTO locations(location_id,location_name) VALUES (35,'Dakota');
INSERT INTO locations(location_id,location_name) VALUES (36,'Dhoby Ghaut');
INSERT INTO locations(location_id,location_name) VALUES (37,'Dover');
INSERT INTO locations(location_id,location_name) VALUES (38,'Downtown');
INSERT INTO locations(location_id,location_name) VALUES (39,'Esplanade');
INSERT INTO locations(location_id,location_name) VALUES (40,'Eunos');
INSERT INTO locations(location_id,location_name) VALUES (41,'Expo');
INSERT INTO locations(location_id,location_name) VALUES (42,'Farrer Park');
INSERT INTO locations(location_id,location_name) VALUES (43,'Farrer Road');
INSERT INTO locations(location_id,location_name) VALUES (44,'Fort Canning');
INSERT INTO locations(location_id,location_name) VALUES (45,'Geylang Bahru');
INSERT INTO locations(location_id,location_name) VALUES (46,'Gul Circle');
INSERT INTO locations(location_id,location_name) VALUES (47,'HarbourFront');
INSERT INTO locations(location_id,location_name) VALUES (48,'Haw Par Villa');
INSERT INTO locations(location_id,location_name) VALUES (49,'Hillview');
INSERT INTO locations(location_id,location_name) VALUES (50,'Holland Village');
INSERT INTO locations(location_id,location_name) VALUES (51,'Hougang');
INSERT INTO locations(location_id,location_name) VALUES (52,'Jalan Besar');
INSERT INTO locations(location_id,location_name) VALUES (53,'Joo Koon');
INSERT INTO locations(location_id,location_name) VALUES (54,'Jurong East');
INSERT INTO locations(location_id,location_name) VALUES (55,'Kaki Bukit');
INSERT INTO locations(location_id,location_name) VALUES (56,'Kallang');
INSERT INTO locations(location_id,location_name) VALUES (57,'Kembangan');
INSERT INTO locations(location_id,location_name) VALUES (58,'Kent Ridge');
INSERT INTO locations(location_id,location_name) VALUES (59,'Khatib');
INSERT INTO locations(location_id,location_name) VALUES (60,'King Albert Park');
INSERT INTO locations(location_id,location_name) VALUES (61,'Kovan');
INSERT INTO locations(location_id,location_name) VALUES (62,'Kranji');
INSERT INTO locations(location_id,location_name) VALUES (63,'Labrador Park');
INSERT INTO locations(location_id,location_name) VALUES (64,'Lakeside');
INSERT INTO locations(location_id,location_name) VALUES (65,'Lavender');
INSERT INTO locations(location_id,location_name) VALUES (66,'Little India');
INSERT INTO locations(location_id,location_name) VALUES (67,'Lorong Chuan');
INSERT INTO locations(location_id,location_name) VALUES (68,'MacPherson');
INSERT INTO locations(location_id,location_name) VALUES (69,'Marina Bay');
INSERT INTO locations(location_id,location_name) VALUES (70,'Marina South Pier');
INSERT INTO locations(location_id,location_name) VALUES (71,'Marsiling');
INSERT INTO locations(location_id,location_name) VALUES (72,'Marymount');
INSERT INTO locations(location_id,location_name) VALUES (73,'Mattar');
INSERT INTO locations(location_id,location_name) VALUES (74,'Mountbatten');
INSERT INTO locations(location_id,location_name) VALUES (75,'Newton');
INSERT INTO locations(location_id,location_name) VALUES (76,'Nicoll Highway');
INSERT INTO locations(location_id,location_name) VALUES (77,'Novena');
INSERT INTO locations(location_id,location_name) VALUES (78,'one-north');
INSERT INTO locations(location_id,location_name) VALUES (79,'Orchard');
INSERT INTO locations(location_id,location_name) VALUES (80,'Outram Park');
INSERT INTO locations(location_id,location_name) VALUES (81,'Pasir Panjang');
INSERT INTO locations(location_id,location_name) VALUES (82,'Pasir Ris');
INSERT INTO locations(location_id,location_name) VALUES (83,'Paya Lebar');
INSERT INTO locations(location_id,location_name) VALUES (84,'Pioneer');
INSERT INTO locations(location_id,location_name) VALUES (85,'Potong Pasir');
INSERT INTO locations(location_id,location_name) VALUES (86,'Promenade');
INSERT INTO locations(location_id,location_name) VALUES (87,'Punggol');
INSERT INTO locations(location_id,location_name) VALUES (88,'Queenstown');
INSERT INTO locations(location_id,location_name) VALUES (89,'Raffles Place');
INSERT INTO locations(location_id,location_name) VALUES (90,'Redhill');
INSERT INTO locations(location_id,location_name) VALUES (91,'Rochor');
INSERT INTO locations(location_id,location_name) VALUES (92,'Sembawang');
INSERT INTO locations(location_id,location_name) VALUES (93,'Sengkang');
INSERT INTO locations(location_id,location_name) VALUES (94,'Serangoon');
INSERT INTO locations(location_id,location_name) VALUES (95,'Simei');
INSERT INTO locations(location_id,location_name) VALUES (96,'Sixth Avenue');
INSERT INTO locations(location_id,location_name) VALUES (97,'Somerset');
INSERT INTO locations(location_id,location_name) VALUES (98,'Stadium');
INSERT INTO locations(location_id,location_name) VALUES (99,'Stevens');
INSERT INTO locations(location_id,location_name) VALUES (100,'Tai Seng');
INSERT INTO locations(location_id,location_name) VALUES (101,'Tampines East');
INSERT INTO locations(location_id,location_name) VALUES (102,'Tampines West');
INSERT INTO locations(location_id,location_name) VALUES (103,'Tampines');
INSERT INTO locations(location_id,location_name) VALUES (104,'Tan Kah Kee');
INSERT INTO locations(location_id,location_name) VALUES (105,'Tanah Merah');
INSERT INTO locations(location_id,location_name) VALUES (106,'Tanjong Pagar');
INSERT INTO locations(location_id,location_name) VALUES (107,'Telok Ayer');
INSERT INTO locations(location_id,location_name) VALUES (108,'Telok Blangah');
INSERT INTO locations(location_id,location_name) VALUES (109,'Tiong Bahru');
INSERT INTO locations(location_id,location_name) VALUES (110,'Toa Payoh');
INSERT INTO locations(location_id,location_name) VALUES (111,'Tuas Crescent');
INSERT INTO locations(location_id,location_name) VALUES (112,'Tuas Link');
INSERT INTO locations(location_id,location_name) VALUES (113,'Tuas West Road');
INSERT INTO locations(location_id,location_name) VALUES (114,'Ubi');
INSERT INTO locations(location_id,location_name) VALUES (115,'Upper Changi');
INSERT INTO locations(location_id,location_name) VALUES (116,'Woodlands North');
INSERT INTO locations(location_id,location_name) VALUES (117,'Woodlands South');
INSERT INTO locations(location_id,location_name) VALUES (118,'Woodlands');
INSERT INTO locations(location_id,location_name) VALUES (119,'Woodleigh');
INSERT INTO locations(location_id,location_name) VALUES (120,'Yew Tee');
INSERT INTO locations(location_id,location_name) VALUES (121,'Yio Chu Kang');
INSERT INTO locations(location_id,location_name) VALUES (122,'Yishun');
